@Timesoft.Solution.Api.Web4_HostAddress = https://localhost:5002

POST {{Timesoft.Solution.Api.Web4_HostAddress}}/api/leave-calculations/start
Content-Type: application/json
Accept: application/json

{
  "companyCode": "COMPANY_A",
  "loginUserId": "HR_A",
  "departmentCode": "HR",
  "employeeNo": "001",
  "year": 2026
}

###

@CalculationId = replace-with-calculation-id

GET {{Timesoft.Solution.Api.Web4_HostAddress}}/api/leave-calculations/{{CalculationId}}
Accept: application/json
